// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * Analysis
 */
export type Analysis = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    origin: Origin;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Classes
     */
    classes: Array<AnalysisClass>;
};

/**
 * AnalysisClass
 */
export type AnalysisClass = {
    classId: ClassId;
    level?: Level | null;
    /**
     * Instances
     */
    instances: number;
};

/**
 * AnalysisCreate
 */
export type AnalysisCreate = {
    /**
     * Name
     */
    name: string;
    origin: Origin;
    /**
     * Classes
     */
    classes: Array<AnalysisClass>;
};

/**
 * AnalysisList
 */
export type AnalysisList = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    origin: Origin;
    /**
     * Createdat
     */
    createdAt: string;
};

/**
 * AnalysisUpdate
 */
export type AnalysisUpdate = {
    /**
     * Name
     */
    name?: string | null;
    origin?: Origin | null;
    /**
     * Classes
     */
    classes?: Array<AnalysisClass> | null;
};

/**
 * ClassId
 */
export type ClassId = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 76 | 77 | 78 | 79 | 80 | 81 | 82 | 83 | 84 | 85 | 86 | 87 | 88 | 89 | 90;

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Level
 */
export type Level = 0 | 1 | 2 | 3 | 4 | 5 | 6;

/**
 * Origin
 */
export type Origin = 0 | 1 | 2 | 3;

/**
 * PaginatedResponse[AnalysisList]
 */
export type PaginatedResponseAnalysisList = {
    pagination: Pagination;
    /**
     * Elements
     */
    elements: Array<AnalysisList>;
};

/**
 * Pagination
 */
export type Pagination = {
    /**
     * Page
     */
    page: number;
    /**
     * Perpage
     */
    perPage: number;
    /**
     * Total
     */
    total: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListAnalysisApiAnalysesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * Page number
         */
        page?: number;
        /**
         * Per Page
         *
         * Number of items per page
         */
        per_page?: number;
    };
    url: '/api/analyses';
};

export type ListAnalysisApiAnalysesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAnalysisApiAnalysesGetError = ListAnalysisApiAnalysesGetErrors[keyof ListAnalysisApiAnalysesGetErrors];

export type ListAnalysisApiAnalysesGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseAnalysisList;
};

export type ListAnalysisApiAnalysesGetResponse = ListAnalysisApiAnalysesGetResponses[keyof ListAnalysisApiAnalysesGetResponses];

export type CreateAnalysisApiAnalysesPostData = {
    body: AnalysisCreate;
    path?: never;
    query?: never;
    url: '/api/analyses';
};

export type CreateAnalysisApiAnalysesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAnalysisApiAnalysesPostError = CreateAnalysisApiAnalysesPostErrors[keyof CreateAnalysisApiAnalysesPostErrors];

export type CreateAnalysisApiAnalysesPostResponses = {
    /**
     * Successful Response
     */
    201: Analysis;
};

export type CreateAnalysisApiAnalysesPostResponse = CreateAnalysisApiAnalysesPostResponses[keyof CreateAnalysisApiAnalysesPostResponses];

export type DeleteAnalysisApiAnalysesAnalysisIdDeleteData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
    };
    query?: never;
    url: '/api/analyses/{analysis_id}';
};

export type DeleteAnalysisApiAnalysesAnalysisIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnalysisApiAnalysesAnalysisIdDeleteError = DeleteAnalysisApiAnalysesAnalysisIdDeleteErrors[keyof DeleteAnalysisApiAnalysesAnalysisIdDeleteErrors];

export type DeleteAnalysisApiAnalysesAnalysisIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAnalysisApiAnalysesAnalysisIdDeleteResponse = DeleteAnalysisApiAnalysesAnalysisIdDeleteResponses[keyof DeleteAnalysisApiAnalysesAnalysisIdDeleteResponses];

export type GetAnalysisDetailApiAnalysesAnalysisIdGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
    };
    query?: never;
    url: '/api/analyses/{analysis_id}';
};

export type GetAnalysisDetailApiAnalysesAnalysisIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisDetailApiAnalysesAnalysisIdGetError = GetAnalysisDetailApiAnalysesAnalysisIdGetErrors[keyof GetAnalysisDetailApiAnalysesAnalysisIdGetErrors];

export type GetAnalysisDetailApiAnalysesAnalysisIdGetResponses = {
    /**
     * Successful Response
     */
    200: Analysis;
};

export type GetAnalysisDetailApiAnalysesAnalysisIdGetResponse = GetAnalysisDetailApiAnalysesAnalysisIdGetResponses[keyof GetAnalysisDetailApiAnalysesAnalysisIdGetResponses];

export type UpdateAnalysisApiAnalysesAnalysisIdPatchData = {
    body: AnalysisUpdate;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
    };
    query?: never;
    url: '/api/analyses/{analysis_id}';
};

export type UpdateAnalysisApiAnalysesAnalysisIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAnalysisApiAnalysesAnalysisIdPatchError = UpdateAnalysisApiAnalysesAnalysisIdPatchErrors[keyof UpdateAnalysisApiAnalysesAnalysisIdPatchErrors];

export type UpdateAnalysisApiAnalysesAnalysisIdPatchResponses = {
    /**
     * Successful Response
     */
    200: Analysis;
};

export type UpdateAnalysisApiAnalysesAnalysisIdPatchResponse = UpdateAnalysisApiAnalysesAnalysisIdPatchResponses[keyof UpdateAnalysisApiAnalysesAnalysisIdPatchResponses];

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Response Read Root  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadRootGetResponse = ReadRootGetResponses[keyof ReadRootGetResponses];
